name    'pulse00-hazelcast'
version '0.3.1'
source 'https://github.com/pulse00/puppet-hazelcast'
author 'pulse00'
license 'The MIT License (MIT)'
summary 'Hazelcast module'
description 'Hazelcast module'
project_page 'https://github.com/pulse00/puppet-hazelcast'

dependency 'puppetlabs/puppetlabs-java', '>= 1.1.0'
